[step1] github(ui layer)
next-step/android-github-compose pull request #16
Opened 2024-09-01 07:02 UTC by jihoi-kang

안녕하세요.
Github UI layer 리뷰 잘 부탁드립니다.

![Screenshot_20240901-160035_GitHub](https://github.com/user-attachments/assets/6ee05eea-9a3e-42ce-943f-1d603a1804fd)

2024-09-01 23:11 UTC, laco-dev requested changes
2단계 미션 고생 많으셨습니다.

테마를 사용하는 기본적인 방법을 학습하는 단계이니 만큼 챙기고 넘어가면 좋을 것 같습니다.
실제 현업에서 개발할 때에도 테마를 기본으로 사용하기 때문에 남겨드린 내용 참고해서 확인 부탁드립니다.

2024-09-01 23:11 UTC, laco-dev commented on app/src/main/java/nextstep/github/ui/repository/RepositoryListActivity.kt
> +        }
MaterialTheme가 정상적으로 적용이 되고 있을까요?

2024-09-01 23:11 UTC, laco-dev commented on app/src/main/java/nextstep/github/ui/repository/component/RepositoryListTopBar.kt
> +}
개인적인 의견이지만 private 함수로 위치해도 충분한 경우라면, 저는 굳이 파일 분리를 하지 않는 편이에요.
별도 파일로 있으면 미리보기도 따로 만들어야 하니까요

2024-09-01 23:11 UTC, laco-dev commented on app/src/main/java/nextstep/github/ui/theme/Color.kt
> +val OUTLINE_VARIANT = Color(0xFFCAC4D0)
테마를 이용해 색상을 지정하는 방법을 학습 해 보시면 좋을 것 같아요
실제로 사용할 때는 아래와 같이 사용됩니다.

```kotlin
// Don't
background(color = SURFACE)

// Do
background(color = MaterialTheme.colorScheme.surface)
```

https://developer.android.com/codelabs/jetpack-compose-theming?hl=ko#0

2024-09-01 23:11 UTC, laco-dev commented on app/src/main/java/nextstep/github/ui/repository/RepositoryListViewModel.kt
> +        }
직접 Factory 만드는 방법이 이전과 많이 바뀌었네요.. 신기하군요 😓

2024-09-01 23:11 UTC, laco-dev commented on app/src/main/java/nextstep/github/ui/repository/RepositoryListScreen.kt
> +                    HorizontalDivider(color = OUTLINE_VARIANT)
테마가 적용된다면 지정하는 컬러 값에 대해서도 생략할 수 있게 됩니다.
*HorizontalDivider가 사용하는 기본 컬러가 어떤 방식으로 적용되는지를 확인

2024-09-02 01:10 UTC, jihoi-kang commented on app/src/main/java/nextstep/github/ui/repository/component/RepositoryListTopBar.kt
> +}
넵 웬만하면 컴포넌트로 분리 가능하면 파일로 구분하는 편이여서 `RepositoryListTopBar`에 preview를 추가하였습니다.

2024-09-02 01:18 UTC, jihoi-kang commented on app/src/main/java/nextstep/github/ui/repository/RepositoryListViewModel.kt
> +        }
아하 많이 바뀌었나요? ㅎㅎ 보통 `Hilt`에서 주입받아서 사용하다보니 많이 바꼈다는걸 못느꼈네요🥲

2024-09-02 01:22 UTC, jihoi-kang commented on app/src/main/java/nextstep/github/ui/repository/RepositoryListScreen.kt
> +                    HorizontalDivider(color = OUTLINE_VARIANT)
`DividerTokens` 에 `OutlineVariant`로 지정되어 있는것 확인하였습니다-!

2024-09-02 01:48 UTC, jihoi-kang commented on app/src/main/java/nextstep/github/ui/theme/Color.kt
> +val OUTLINE_VARIANT = Color(0xFFCAC4D0)
`Theme`에 등록하여 적용하였습니다.
[da186a7](https://github.com/next-step/android-github-compose/pull/16/commits/da186a7e04620c8a5b37454bc8b336e65cacc0b0)

2024-09-02 03:04 UTC, laco-dev approved these changes
좋습니다.

다음 미션에서 또 이야기 나눠보면 좋을 것 같아요. 👍🏻

2024-09-02 03:04 UTC, merged