4단계 - GitHub(인기 저장소)
next-step/android-github-compose pull request #26
Opened 2024-09-04 08:08 UTC by sjjeong

- 이전 리뷰의 코멘트 반영했습니다.
- Star 개수를 보여주고 50개가 넘으면 HOT을 보여주는 ui 추가했습니다.

2024-09-05 07:17 UTC, namjackson requested changes
안녕하세요 석준님! 
4단계 잘 구현해주셨네요! 
잘 구현해주셔서 크게 코멘트 드릴부분이 없네요! 
고생하셨습니다!

2024-09-05 07:17 UTC, namjackson commented on app/src/main/java/nextstep/github/ui/model/GithubRepositoryModel.kt
> +        isHot = (stars ?: 0) >= HOT_MINIMUM_STARS,
> (선택사항) domain 패키지를 만들어 비즈니스 로직을 캡슐화한다.

라는 선택적 요구사항도 있으니, 여유가 되시면 적용해보셔도 좋아요 :)

2024-09-05 07:17 UTC, namjackson commented on app/src/main/java/nextstep/github/ui/view/github/repository/GithubRepositoryListUiState.kt
> +    data class Found(val repositories: List<GithubRepositoryModel>) : GithubRepositoryListUiState
개인적인 의견이니 의견만 주셔도 좋을거 같아요
스타일의 차이긴하지만, UiState에서 Found, NotFound는 데이터 관점으로 보이는거 같아요 
Ui관점에서 좀더 명확한 표현 Empty, Repositories 같은 표현이 좀더 어울리지 않나욤?

2024-09-05 07:19 UTC, namjackson commented
혹시 추가 수정이나, 미션 선택사항을 구현하실수 있으니, 
마지막으로 Changes requested 드렸습니다!
이대로 미션 종료를 원하시면 그냥 리뷰요청 해주세요 :)
깃헙미션 고생하셨습니다!

2024-09-05 13:21 UTC, sjjeong commented on app/src/main/java/nextstep/github/ui/view/github/repository/screen/GithubRepositoryListItem.kt
>  private fun GithubRepositoryListItemPreview() {
저는 Preview와 Test 둘다 현재 제가 검증하고자 하는 부분까지만 만들어요!
물론 모든 케이스가 커버되도록 작성하면 좋다고 생각합니다!

2024-09-05 13:23 UTC, sjjeong commented on app/src/main/java/nextstep/github/ui/view/github/repository/GithubRepositoryListUiState.kt
> +    data class Found(val repositories: List<GithubRepositoryModel>) : GithubRepositoryListUiState
제가 최근에 서버개발을 잠깐 해봤는데 거기서 익숙하던 패턴이라 앱에서도 동일하게 사용했네요.
데이터 관점으로 보이는게 맞고 UI관점으로 명확한 표현으로 바꾸는게 더 어울릴것 같네요

2024-09-06 12:26 UTC, sjjeong commented on app/src/main/java/nextstep/github/ui/view/github/repository/screen/GithubRepositoryListItem.kt
>  private fun GithubRepositoryListItemPreview() {
9d7b1df5ce8c5f6a53f05bca0f9caa7490b2d232

2024-09-06 12:26 UTC, sjjeong commented on app/src/main/java/nextstep/github/ui/view/github/repository/GithubRepositoryListUiState.kt
> +    data class Found(val repositories: List<GithubRepositoryModel>) : GithubRepositoryListUiState
efd1189f534d6adce91beea657b44739ad072ae8

2024-09-06 12:26 UTC, sjjeong commented on app/src/main/java/nextstep/github/ui/model/GithubRepositoryModel.kt
> +        isHot = (stars ?: 0) >= HOT_MINIMUM_STARS,
05a24b3f61cfd41b3d1e5937f0e1e70ede921ada

2024-09-07 08:49 UTC, namjackson approved these changes
안녕하세요 석준님!
피드백 잘 적용해주셨네요! 
Github 미션 고생하셨습니다 :)
미션은 여기서 종료하겠습니다! 고생하셨습니다!

2024-09-07 08:49 UTC, namjackson commented on app/src/main/java/nextstep/github/domain/GetRepositoriesUseCase.kt
> +import nextstep.github.model.GithubRepositoryDto
도메인 영역을 잘 분리해주셨네요 👍 
사소하지만, GithubRepository 인터페이스나 Hot 로직도 도메인으로 분리할수도 있을거같아요 :)

2024-09-07 08:49 UTC, merged